[package]
name = "link-canonical"
version = "0.1.0"
authors = ["Kim Altintop <kim@eagain.st>"]
edition = "2018"
license = "GPL-3.0-or-later"

description = "Canonical serialisation formats, currently OLPC Canonical JSON"

[lib]
doctest = false
test = false

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11"
thiserror = "1.0"
unicode-normalization = "0.1"
