steps:
  - label: "Build, lint, test"
    commands:
      - "ci/run"
    agents:
      production: "true"
      platform: "linux"
    env:
      DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-link-build@sha256:b50248204078e514b02b3159d4b545942084bc621624a9354e30f1a1f9930bad"
      DOCKER_FILE: .buildkite/docker/rust-nightly/Dockerfile

  - label: "Render Spec"
    commands:
      - "cd spec"
      - "make clean all"
      - "git diff --exit-code -- spec/out"
    agents:
      production: "true"
      platform: "linux"
    env:
      DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-link-pandoc@sha256:eb1d9592d83fa5edad1b626a71b53aa586c64a5a7e7bb4158256d6265e1ac1a9"
      DOCKER_FILE: .buildkite/docker/pandoc/Dockerfile
