steps:
  # This step is essentially a no-op. Since it blocks all other steps, we avoid
  # triggering `n` image builds when updating the `DOCKER_IMAGE`. Note that it
  # still saves about 20sec to pin the image to a SHA256 after an upgrade.
  - label: "Build container"
    commands:
      - ".buildkite/env"
      - ".buildkite/build-container"
    agents: &build-agent
      production: "true"
      platform: "linux"
    env: &build-docker
      DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-link-seedling-build@sha256:b36bfdee81c6a175275c7aeef0698b4443b554fa96b8033f92849dcedd5bf5f3"
      DOCKER_FILE: .buildkite/docker/rust/Dockerfile

  - wait

  - label: "Build + Test"
    commands:
      - ".buildkite/env"
      - "ci/build-test"
    artifact_paths:
      - "Cargo.lock"
    agents: *build-agent
    env: *build-docker

  - label: "fmt + clip"
    skip:
    commands:
      - ".buildkite/env"
      - "ci/clippy"
    artifact_paths:
      - "Cargo.lock"
    agents: *build-agent
    env: *build-docker

  - label: "Deny"
    skip:
    commands:
      - ".buildkite/env"
      - "ci/advisory"
    artifact_paths:
      - "Cargo.lock"
    agents: *build-agent
    env: *build-docker

  - label: "Docs"
    commands:
      - ".buildkite/env"
      - "ci/docs"
    artifact_paths:
      - "Cargo.lock"
    agents: *build-agent
    env: *build-docker
