steps:
  - label: "Build, test, doc"
    commands:
      - "ci/build-test"
      - "ci/docs"
    artifact_paths:
      - "Cargo.lock"
    agents: &build-agent
      production: "true"
      platform: "linux"
    env: &build-docker
      DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-link-seedling-build@sha256:bbf2fa12555886b7f279bb1ba7997090611f3c23a178fd27bb06f70693acd8af"
      DOCKER_FILE: .buildkite/docker/rust/Dockerfile

  - label: "Lint and clip"
    commands:
      - "ci/clippy"
    artifact_paths:
      - "Cargo.lock"
    agents: *build-agent
    env: *build-docker

  - label: "Deny"
    commands:
      - "ci/advisory"
    artifact_paths:
      - "Cargo.lock"
    agents: *build-agent
    env: *build-docker


  - label: "Render Spec"
    skip: "This spec is outdated. Should render new spec once complete-ish."
    commands:
      - "cd spec"
      - "make clean all"
      - "git diff --exit-code -- spec/out"
    agents:
      production: "true"
      platform: "linux"
    env:
      DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-link-pandoc@sha256:eb1d9592d83fa5edad1b626a71b53aa586c64a5a7e7bb4158256d6265e1ac1a9"
      DOCKER_FILE: .buildkite/docker/pandoc/Dockerfile
