#!/usr/bin/env bash
set -eou pipefail

echo '--- Build'
cargo build --workspace

echo '--- Test (replication v2)'
RUST_LOG=error ssh-agent cargo test --workspace

echo '--- Test (replication v3)'
RUST_LOG=error ssh-agent cargo test --workspace  --features replication-v3
