#!/usr/bin/env bash
set -eoux pipefail

# Force clippy to consider all local sources
# https://github.com/rust-lang/rust-clippy/issues/4612
find . -name "*.rs" -not -path "./target/*" -exec touch "{}" +
cargo clippy --all-targets -- -D warnings

find . -name "*.rs" -not -path "./target/*" -exec touch "{}" +
cargo clippy --all-targets --features replication-v3 -- -D warnings
