grap: trap 'podman stop graphite-exporter; podman rm graphite-exporter;' EXIT > /dev/null; podman run --name graphite-exporter --network host --rm docker.io/prom/graphite-exporter --web.listen-address="127.0.0.1:9180"
prom: trap 'podman stop prometheus; podman rm prometheus;' EXIT > /dev/null; podman run --name prometheus --network host --rm -v $PWD/theus:/etc/prometheus docker.io/prom/prometheus --config.file=/etc/prometheus/config.yaml --web.listen-address="127.0.0.1:9090"
peer: cargo run --bin ephemeral-peer
