#!/usr/bin/env bash
set -eou pipefail

# Usage: `patch-create new-feature v1`
# where:
#   * `new-feature` is the name given to the patch
#   * `v1` is the version of the patch
#
# Creates a local, signed tag with the name `patches/new-feature/v1`

PREFIX=$1
VERSION=$2

git tag patches/${PREFIX}/${VERSION}
