[package]
name = "radicle-link-test"
description = "Common testing utilities"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
assert_matches = "1"
anyhow = "1"
async-trait = "0"
env_logger = "0"
either = "1"
futures = ">= 0.3"
futures-await-test = "0"
futures_ringbuf = "0"
lazy_static = "1"
log = "0.4"
minicbor = ">= 0.6, 0"
multibase = "0.9"
multihash = "0.11"
nonempty = "0.6"
nonzero_ext = "0.2"
pretty_assertions = "0"
proptest = "0"
radicle-keystore = "0"
regex = "1.3"
serde = "1"
serde_json = "1"
sha-1 = "0.9"
sized-vec = "0.3"
tempfile = "3"
typenum = "1.13"
tokio = "1.1"
tracing = ">= 0.1"
tracing-subscriber = ">= 0.2"
unicode-normalization = "0.1"
url = "2.1"
webpki = "0.21"

[dependencies.git2]
version = "0.13"
default-features = false
features = []

[dependencies.librad]
path = "../librad"

[dependencies.radicle-git-ext]
path = "../git-ext"

[dependencies.rand]
version = "0.7"
features = [ "small_rng" ]

# Note: this MUST always match the exact patch version `quinn` uses
[dependencies.rustls]
version  = "0.19"
features = ["logging", "dangerous_configuration"]

[dependencies.zeroize]
version = "1.1"
features = ["zeroize_derive"]
