[package]
name = "radicle-seed"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
librad = { path = "../librad" }
async-trait = "0.1"
thiserror = "1.0"
tokio = "0.2"
futures = "0.3"
argh = "0.1.3"
log = { version = "0.4", features = ["std"] }
chrono = "0.4"

[dependencies.radicle-keystore]
git = "https://github.com/radicle-dev/radicle-keystore.git"
rev = "27c9a7b8ce5b87d2be3703f7a3290fa7a0552fc6"
