#!/usr/bin/env bash
set -eou pipefail

echo '--- Build'
cargo build --workspace --all-features

echo '--- Test'
#RUST_LOG=error cargo test --workspace --all-features
RUST_LOG=librad=trace cargo test test::integration::librad::smoke::clone::when_connected
