#!/usr/bin/env bash
set -eou pipefail

echo '--- Build'
cargo build --workspace --all-features

echo '--- Test'
RUST_LOG=librad::rate_limit=trace,librad::net::protocol::cache=trace,librad::net::protocol=trace cargo test --workspace --all-features
