#!/usr/bin/env bash
set -eou pipefail

echo '--- Formatting'
cargo fmt -- --check

echo '--- Clippy'
# Force clippy to consider all local sources
# https://github.com/rust-lang/rust-clippy/issues/4612
find -name ".rs" -not -path "./target/*" -exec touch "{}" +
cargo clippy --all-targets --all-features -- -D warnings
