= RFC: RadiCLI
:author: @FintanH
:revdate: 2021-06-04
:revremark: draft
:toc:
:toc-placement: preamble

* Author: {author}
* Date: {revdate}
* Status: {revremark}
* Community discussion: n/a
* Tracking Issue: https://github.com/radicle-dev/radicle-link/issues/742

== Motivation

RFC-682 set the stage for defining the architecture of applications
built on top of `<<radicle-link>>`. This RFC wishes to build on top of
this specification and fill in the gaps around the CLI component and
its organisation. As dogfooding our own solutions is on our long-term
roadmap, this team wants to provide tooling that they will maintain
and use themselves.

== Overview

This proposal will outline a binary called `rad`, what it will
provide, and how it can be extended. Following this we provide details
on the interaction -- or lack there of -- with the peer-to-peer
daemon.

We also provide a proposal of how any CLI tool will have
access to any keys, as well as what needs to be completed for
providing this.

We close out with how the core components will be organised within
`radicle-link` and `<<radicle-bins>>` as well as providing the first
iteration of the core set of subcommands.

== Terminology and Conventions

The key words "`MUST`", "`MUST NOT`", "`REQUIRED`", "`SHALL`", "`SHALL NOT`",
"`SHOULD`", "`SHOULD NOT`", "`RECOMMENDED`", "`NOT RECOMMENDED`", "`MAY`", and
"`OPTIONAL`" in this document are to be interpreted as described in <<RFC2119>>
and <<RFC8174>> when, and only when, they appear in all capitals, as shown here.


== One `rad` to Rule Them All

[quote]
-------
One ring to rule them all, one ring to find them,
One ring to bring them all, and in the darkness bind them;
-------
-- J.R.R. Tolkein, Fellowship of the Ring

The integral part of this proposal is that there will be one binary,
`rad`, that will be the foundation for all other subcommands. It will
define the global parameters and how to extend it.

We will discuss these in the following two sections.

== The Fellowship of the `rad`

[quote]
--------
“I can’t carry it for you, but I can carry you.” – Sam Gamgee
--------
-- J.R.R. Tolkien, The Return of the King

To allow the ecosystem of commands to be extended by ourselves and
others in the community it will be necessary to extend the `rad`
command with further subcommands. The details of this are outlined in
<<arch-cli, RFC-682#CLI>>, however, we will give a quick overview here for the sake
of the reader.

Taking inspiration from tools such as `git` and `cargo`, we propose
that the `rad` binary can be extended by placing another
binary on the users `$PATH` (or `%PATH%` on Windows). This
binary MUST follow the naming convention of `rad-*`. To reiterate
here, these new commands MUST NOT override the core set outlined here
(nor in further RFCs).

== Global Parameters

Many subcommands will likely want to share a set of options. These
options, dubbed as "global parameters" here, will be a defined set --
exported from `radicle-link` for re-use -- that the base `rad` command
will always receive and pass onto the subcommand being called.

These parameters will be prefixed by `rad-`, signfiying that they are
from the `radicle-link` namespace and are reserved names.

Subcommands, including the <<Core>> subcommands, SHOULD accept these
parameters as well. Exceptions can be made for commands that truly
don't need these values, e.g. `rad-profile` will not need the
`--rad-profile` option.

To illustrate the passing of the value to the subcommand, we will
suppose a subcommand called `rad-issues`. The `--rad-profile`
parameter can be used like the following:
```
$ rad --rad-profile abc issues create ...
```

or:
```
$ rad issues --rad-profile abc create
```

If the parameter is specified in both positions, i.e.
```
$ rad --rad-profile abc issues --rad-profile def create
```
then the first will take precedence. The result of the above will be
the profile `abc`.

Some parameters can also be specified by environment variables. The
arguments passed to subcommands will be given by the environment
variable, if and only if, the command line argument is not specified.
For example, `$RAD_PROFILE` is used within `radicle-link`. If this is
set without the use of `--rad-profile`, then the value is taken from
`$RAD_PROFILE`. However, if `--rad-profile` is specified as well as
`$RAD_PROFILE`, then the value of `--rad-profile` takes precedence.

Other subcommands that are written in the target language (currently
Rust) will be able to import a `struct` for reuse. If the subcommand
is in another target language it SHOULD add these parameters to its
parameter list.

We list these parameters here, but it is NOT an exhaustive list:

* `rad-verbose`
* `rad-quiet`
* `rad-profile := active (default) | <profile-id>`

== CLI Events

The execution of a CLI subcommand could potentially result in an
interesting event. For example, if Upstream is
running and I create a project via the CLI, then a good user
experience is that the Upstream is updated with the new project
(without refreshing). In this case, the event is the creation of the
project.

In <<arch-pubsub, RFC-682#PubSub>>, a PubSub component was proposed --
with a detailed specification being left to a future RFC. We will
assume the existence of this component here. The CLI commands in this
RFC MAY publish interesting events to the PubSub component. This will
allow other applications to react upon seeing these events via
subscriptions to the PubSub component.

Other subcommands MAY also publish interesting events, as long as they
adhere to the specification of the future RFC. They SHALL reuse any
events defined as part of the <<Core>> commands. That is to say, there
will be a core set of events that should not be overridden, but rather
reused if needs be.

== Key Access

<<arch-sigs, RFC-682#Signatures>> outlined the signing of Radicle data. This is essential to
this RFC as commands that write to the storage generally need access
to the secret key, whether for signing data or proof of ownership to
the storage. For most (if not all) read-only commands, no access to
the secret key is needed.

To achieve the goals of having a read-only storage and using
`<<ssh-agent>>` for signing, we propose the following should be
implemented:

. `ssh-agent` compatibility with `<<radicle-keystore>>`, which has been
started in `<<rk-17, radicle-keystore#17>>`.
. A subcommand `rad-profile-ssh-add` for adding one's secret key to the
`ssh-agent` using the supplied constraints, e.g. ask for password.

== Library/Command Organisation

As proposed here, `radicle-link` will provide a core set of
functionality. Something this document wishes to standardise is the
organisation of these components. The author sees two options:

. One binary that defines the core subcommands
. Many binaries that take advantage of the subcommand mechanism

Pros of *1.*:

* One-stop shop for all core functionality
* One binary is packaged and distributed

Cons of *1.*:

* Making changes to one subset of the commands could mean a version
  change of the whole binary

Pros of *2.*:

* We will be organising commands as libraries (as per RFC-682) — so
  modular commands would mirror this structure well.
* Subcommands can be versioned independently of each other.
* We can dogfood our subcommand functionality

Cons of *2.*:

* Makes it easier to override one of the core commands.
* Many binaries must be packaged and distributed.

The author recommends *1.*. As mentioned, we have a hard requirement
of not allowing the core commands to be overridden. In *2.* this is
_always_ possible.

=== `radicle-bins`

Per <<arch-cli, RFC-682#CLI>>, all subcommands will be provided as
libraries. However, this leaves the question of where the binary might
live. So far, it has been an unspoken formalism that all binaries live
in `radicle-bins` where we can provide a `Cargo.lock` file. All
functionality will live in `radicle-link`, including the `main`
function, and the entry in `radicle-bins` will be a thin wrapper
around this function.

== Core

[quote]
------
We swears to serve the master of the precious. We will swear on
the…on the precious.
------
-- Gollum, The Two Towers

With all the details in place, we define a non-exhaustive list of the
core commands that we wish to include for the first iteration. More
components MAY be added as the result of future RFCs. We SHALL keep a
list of the core commands as part of the `radicle-link` documentation.

=== `rad-identities`

The `rad identities` subcommand provides the management of identity
documents and their metadata. It is further split into subcommands
which we sketch out below:

* `project [ create | get | list | update | checkout | review ]` --
  modify and retrieve `Project` identities.
* `person [ create | get | list | update | checkout | review ]` --
  modify and retrieve `Person` identities.
* `any [ get | list ]` -- retrieve identities where the caller does not
  know what kind of identity it is. The CLI will make a best-effort to
  infer the type, or else return an opaque blob.
* `local [ set | get | default ]` -- modify or retrieve a local identity
* `tracking [ track | untrack | list ]` -- modify and list the tracking
  graph for a given identity.
* `rad-refs [ self | signed | delegates | delegate ]` -- retrieve the
  blobs that live under `rad/<refname>`
* `refs [ heads | notes | tags | category ]` -- list the reference names.
  under the respective category, where `category` is a user supplied category.

=== `rad-replicate`

* `ask` -- tell the `daemon` that you wish to replicate the
  given URN. Pending <<rl-141, radicle-link#141>>.
* `status` -- retrieve the status of a URN that we have `ask`ed for.
* `list` -- list the URNs that we have asked for but have not yet replicated.
* `direct` -- if the peer/address are known for the given URN,
  attempt to replicate the identity. This requires the activation of
  the peer-to-peer daemon.

=== `rad-profile`

This command will provide the management of keys and the `Profile`
construct in `librad`. The following actions will be defined:

* `create`— generate a new `Profile`-- setting up a new key and any
  related infrastructure for the profile, e.g. storage.
* `get`— get the current `Profile`'s identifier.
* `set`— set the current `Profile` to the identifier.
  passed in.
* `list`— list the available `Profile` identifiers.
* `ssh-add`— add the current `Profile`'s key to the `ssh-agent`.

=== `rad-daemon`

This command provides introspection into the peer-to-peer daemon.

* `peers` -- get the list of currently connected peers
* `membership` -- get the membership list for the peer-to-peer
  daemon's membership view.
* `stats` -- request the stats of the peer-to-peer daemon, i.e. a
  summary of peers and members.

=== Note on Output

Some operations will result in data that should be output, for
example, retrieving a `Project` from the store will return the
metadata for that project. As per <<arch-cli, RFC-682#CLI>>:

[quote]
-------

Each subcommand MUST expose its functionality as a linkable library,
and provide CBOR <<RFC8949>> serialisation for its arguments and outputs.
-------

The output should, however, not be limited to CBOR. We will provide an
option, `--output`, that will give the caller the option to output
into another format. The initial options will be:

. `json`
. `cbor`

with the default being `json` since the CLIs are user-centric
applications and human-readable footnote:disclaimer[For some
definition of human-readble] output would be desirable. More output
types MAY be proposed in future RFCs.

== Documentation

During review, the question of documentation was put forward. The
ideal situation is that the documentation provided in the codebase is
also used for a rendered page, wherever that may be hosted. We would,
however, prefer to avoid duplicating this knowledge and allowing it to
go out of date.

Other projects such as <<ipfs>> and <<kubectl>> seem to achieve this
and provide us with some inspiration. How exactly these two projects
achieve this is still not quite clear to the author, but we will
outline two potential avenues for generating documentation.

The argument parsing libraries in Rust allow the help documentation to
be generated from the data definitions. In `<<argh>>`, the
documentation is generated from the inline code documentation. In
`<<clap>>` the help is generated by specifying an `App` structure, or
to have a more `argh`-like experience, `structopt` can be used.  This
leads us to the two options:

1. we parse and generate documentation based off the help output
2. we piggyback on `argh`/`structopt` to create macros that output
markdown

The second option seems like the most preferable option since a
portion of the problem is already solved, that is parsing. The other
portion of the problem would be outputting the markdown.

On the author's search for answers, the `<<clap-md>>` project was
discovered. It is currently unmaintained, but it has potential to be
updated. The crux is that it would require `clap-3.0.0` which is
currently only in beta (and thus its API may be unstable). One benefit
is that `structopt` will be folded into `clap`
footnote:[https://github.com/clap-rs/clap/blob/master/FAQ.md#how-does-clap-compare-to-structopt].

The other option is to use `argh`'s help generation infrastructure and
build something similar to `clap-md`. An issue was created
footnote:[https://github.com/google/argh/issues/102] but, as of
writing, no response has been received.

The author is under the impression that going through the route of
using `clap` would be preferable. While `argh` is an easy to use
project, it does not seem as actively maintained as `clap`.

The recommendation would be to begin the work using `clap-2.33` along
with `structopt`. When `clap-3.0.0` is released, `structopt` can be
removed and an updated version of `clap-md` can be used to output
markdown.

We will not recommend how we will host documentation here, but rather
leave it up to a team discussion at another point in time.

[bibliography]
== References

* [[[RFC2119]]] https://datatracker.ietf.org/doc/html/rfc2119
* [[[RFC8174]]] https://datatracker.ietf.org/doc/html/rfc8174
* [[[RFC8949]]] https://datatracker.ietf.org/doc/html/rfc8949
* [[[arch-cli]]] https://github.com/radicle-dev/radicle-link/blob/master/docs/rfc/0682-application-architecture.adoc#cli
* [[[arch-orch]]]
  https://github.com/radicle-dev/radicle-link/blob/master/docs/rfc/0682-application-architecture.adoc#process-orchestration
* [[[arch-pubsub]]] https://github.com/radicle-dev/radicle-link/blob/master/docs/rfc/0682-application-architecture.adoc#pubsub
* [[[arch-sigs]]] https://github.com/radicle-dev/radicle-link/blob/master/docs/rfc/0682-application-architecture.adoc#signatures
* [[[argh]]] https://github.com/google/argh
* [[[clap]]] https://github.com/clap-rs/clap
* [[[clap-md]]] https://github.com/rust-cli/clap-md
* [[[ipfs]]] https://docs.ipfs.io/reference/cli/
* [[[kubectl]]] https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands
* [[[radicle-bins]]] https://github.com/radicle-dev/radicle-bins/
* [[[radicle-link]]] https://github.com/radicle-dev/radicle-link/
* [[[radicle-keystore]]] https://github.com/radicle-dev/radicle-keystore/
* [[[rk-17]]] https://github.com/radicle-dev/radicle-keystore/pull/17
* [[[rl-141]]] https://github.com/radicle-dev/radicle-link/issues/141
* [[[ssh-agent]]] https://datatracker.ietf.org/doc/html/draft-miller-ssh-agent-04
* [[[structopt]]] https://github.com/TeXitoi/structopt
