= RFC: Tracking Storage
Fintan Halpenny <fintan.halpenny@gmail.com>; Kim Altintop <kim@eagain.st>; xla <self@xla.is>

:revdate: 2021-10-12
:revremark: amended
:toc: preamble
:ammend_1: 2022-02-01

* Author: {author_1}, {author_2}, {author_3}
* Date: {revdate}
* Amended: {ammend_1}
* Status: {revremark}
* Discussion: https://lists.sr.ht/~radicle-link/dev/%3Cc2aae5c561e6c1d3b75394de8d570209%40xla.is%3E

== Motivation

The motivation for this RFC is two-fold, as can be seen in the linked
discussion. The first is the want to have a protocol mechanism for
replicating a resource when only the URN is known. The second is the
want to be able to configure the fetching of references for a given
remote.

The <<Current Implementation>> had left us with some limitations,
which informed us for this motivation. Learning from these
limitations, the goals for this proposed, reference-based solution are
to scale concurrently and relieve memory pressure.

== Overview

Given the <<Motivation>>, this RFC proposes a replacement of how
tracking is implemented at the time of writing. It will describe how
the tracking relationships will be stored using git, and the format
for the storage contents.

While replication is stated as a motivation, it is out of scope for
this RFC to propose any novel additions to replication of URNs. It
will, however, propose a modification of the existing protocol
semantics for replication when a peer receives a new gossip message.

== Terminology and Conventions

The key words "`MUST`", "`MUST NOT`", "`REQUIRED`", "`SHALL`", "`SHALL NOT`",
"`SHOULD`", "`SHOULD NOT`", "`RECOMMENDED`", "`NOT RECOMMENDED`", "`MAY`", and
"`OPTIONAL`" in this document are to be interpreted as described in <<RFC2119>>
and <<RFC8174>> when, and only when, they appear in all capitals, as
shown here.

== Storage

The base requirements for tracking are the capabilities of creating,
updating, deleting, and reading the tracking entries along with their
configurations. The keys for this storage are given by a URN and Peer
ID pairing. The value stored for a given key is the configuration for
that tracking entry. The capabilities that we wish to capture
are:

* *track* a URN with an optional Peer ID
* *untrack* a URN and Peer ID
* *list* tracked URN and PeerIDs
* *update* the configuration of a tracking entry for a given URN and
Peer ID
* *get* the configuration of a tracking entry for a given URN and Peer ID

Any storage backend MUST implement these capabilities, using URN
and Peer IDs as keys. Where a tracking relationship is not using a
Peer ID -- in the case that no Peer IDs are known -- a default MUST be
established.

== Configuration

As mentioned in the <<Motivation>>, we wish to be able to configure
which references we fetch for a given remote. The natural place to
configure this is in the entry for a URN/Peer ID pair.

All data that can be fetched is currently organised into pre-existing
categories found in radicle-link's git implementation today -- stored
as git references. The categories enumerated are:

* `rad`
* `cobs`
* `heads`
* `tags`
* `notes`

The `rad` category is necessary for the verification of data exchanged
on the network. The `cobs` category is the home for
application-defined, code-collaboration artifacts. The `heads`,
`tags`, and `notes` categories are well-known in the domain of git.

The `rad` category MUST always be fetched to persist the validity of
the data found within this category.

Since the `cobs` category can vary in structure and size, as well as
being application specific, we allow the filtering of this data.

The remaining categories are consolidated under the key of `"data"`,
and are referred to as data-refs. The filtering on these categories is
all-or-nothing. This choice is made to ensure the reasoning of
replicating git data. If a portion of data is filtered, it becomes
hard to reason whether this is a protocol error or a node filtering
out this data.

The configuration is REQUIRED to be a key/value format. The
following scheme is REQUIRED to be adhered to:

[source,json]
----
{
  "data": bool,
  "cobs": {
    ("*" | <typename>): {
      "policy": <policy> <1>
      "pattern": <pattern> <2>
    }
  }
}
----
<1> `<policy> = "allow" | "deny"`
<2> `<pattern> = "*" | [<object id>]`

[NOTE]
======
. `<typename>` is any valid name for a collaborative object.
. `<object id>` is any valid collaborative object identifier.
. `"*"` is the wildcard for matching all types, or all objects
under `<typename>`.
======

If `"data"` is set to `true` then all data-refs SHALL be
replicated, and none if set to `false`.

The `"cobs"` filter is first based on the `<typename>` -- `"\*"`
meaning _all_ types. For every given typename, the `"pattern"`
specifies which collaborative objects are in question -- `"*"`
meaning _all_ objects for that type. The `"policy"` designates whether
this set of objects are allowed (`"allow"`) or denied (`"deny"`). If
the former, the objects SHALL be replicated to the device. If the
latter, the object SHALL NOT be replicated to the device.

When a policy is created for a type, it is implicit that the opposite
policy holds for the complement of the set. For example, if the
following policy is given:

[source,json,id="cobs-example"]
----
{
  "data": true,
  "cobs": {
    "discussions": { "policy": "deny", "pattern": [1, 2, 3] }
  }
}
----

This implies that any `"discussions"` that are _not_ 1, 2, or 3 are
_allowed_.

If a typename is not specified and if `"*"` is also not specified,
then the typename SHALL NOT be replicated. In the <<cobs-example,
example above>>, only `"discussions"` will be replicated.

Finally, if `"*"` is specified as a `<typename>`, the policy for any
other `<typename>` will take precedence over the catch-all policy. For
example, if the following policy is given:

[source,json]
----
{
  "data": true,
  "cobs": {
    "*": { "policy": "allow", "pattern": "*" },
    "discussions": { "policy": "deny", "pattern": [1, 2, 3] }
  }
}
----

Then the `"discussions"` 1, 2, and 3 are denied, as opposed to being
allowed by the `"*"` policy.

The *default configuration* SHALL be to fetch all data and collaborative objects, i.e.
[source,json,id="default-config"]
----
{
  "data": true,
  "cobs": {
    "*": { "policy": "allow", "pattern": "*" }
  }
}
----

=== Delegates

The data provided by delegates is privileged, as it is generally the
canonical view of the data. It SHALL NOT be possible to filter out any
of the data for a delegate Peer ID. Thus, the configuration for a
delegate Peer ID SHALL be ignored when fetching.

== Git Storage

Given the outlines in <<Storage>> and <<Configuration>>, we propose
the following implementation using git as the storage layer. The
configuration SHALL be stored as a blob and to retrieve this blob we
SHALL use a well formed reference name for a given URN and Peer ID.

=== Tracking Reference

The reference SHALL be of the form:

----
refs/rad/remotes/<namespace>/(<peer id> | default) <1> <2> <3>
----
<1> `<namespace>` is the multibase-multihash encoded hash of the URN
<2> `<peer id>` is the same format as `<namespace>` based on the
public key of the peer
<3> `default` is the value used when a `<peer id>` is not specified

The reference MUST point directly to the SHA identifier of the blob
that contains the configuration. This differs from the usual use of
references pointing directly to commits. This is intended as we do not
want to keep track of the history of changes for the configuration.

=== Configuration Format

The configuration is REQUIRED to use <<Canonical-JSON>>. This provides
a key/value format, while also being hash friendly for git
purposes. If multiple configurations are equivalent, for example the
default configuration, they can all be represented by the same SHA --
saving storage space.

=== Tracking Semantics

To *track* a new peer the reference (see <<Tracking Reference>>) is
created with the given configuration or <<default-config, default
configuration>> if not specified.

To *untrack* a peer, we remove the reference for the given URN and
Peer ID. We then MAY prune any existing references under
`refs/namespaces/<urn>/refs/remotes/<peer>`.

To *list* the remotes for a given URN, we can use the refspec:
----
refs/rad/remotes/<urn>/*
----

To *list* the remotes for all URNs, we can use the refspec:
----
refs/rad/remotes/**/*
----

To *update* a configuration the new configuration blob can be
created and the reference SHALL point to the new SHA.

To *get* a configuration the blob, located by the reference for the
given URN and Peer ID, read into memory.

== Replication

At the time of writing the protocol has a mechanism for replicating
interesting gossip. When a gossip message is received by the running
peer it will replicate the changes if the running peer is tracking the
URN and Peer ID contained in the gossip message _and_ does not already
store the object corresponding to the git SHA inside the message.

We propose here that this be modified to account for the case where
the running peer has tracked a URN without a Peer ID. The conditions
are modified as follows. If the running peer is *only* tracking the
`default` entry, it SHALL replicate the changes. Otherwise, if the
running peer is tracking the URN and Peer ID contained in the gossip
message _and_ does not already store the object corresponding to the
git SHA inside the message.

== Batch Tracking

It is possible for the tracking API to provide a way to batch tracking
operations together. These operations are equivalent to `track` or
`untrack`, along with their parameters.

One such parameter is the given "policy" for tracking or
untracking. The policy describes the expected state of the reference
when performing the `track`/`untrack`. Since the state of the
reference could change due to concurrent modifications, the policy is
used to reject a modification if the expectation is not met.

For `track` we have the following policies:

. `Any` -- perform the `track` regardless of a reference existing or not.
. `MustNotExist` -- perform the `track` iff a reference for that name
*does not exist* already.
. `MustExist` -- perform the `track` iff a reference for that name
*exists* already.

And for `untrack` we have:

. `Any` -- perform the `untrack` regardless of a reference existing or not.
. `MustExist` -- perform the `untrack` iff a reference for that name
*exists* already.

Given a set of `track` and `untrack` operations, along with their
policies, it should be possible to fuse them by simplifying pairs of
operation into a single operation. Here we describe the rules for this
simplification by reasoning about the composition of these operations
with respect to the above policies. The reasoning can be broken down
by case analysis, where we consider the combination of policies and
how they succeed or fail if the reference exists or does not exist.

For each composition, we assume that the `Urn` and `PeerId` are the
same for both operations, and so we omit them.

=== track ∘ track

The parameters `c` and `c'` are the configurations provided for the
tracking relationship.

==== track Any c' ∘ x === track Any c'

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |`track Any c'` overwrites any other `track policy`
|No |Same as above
|===

[cols="1"]
|===
|*Conclusion*
|`track Any c'` will always succeed
|===

==== track MustExist c' ∘ track Any c === track Any c'

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |`track Any c` succeeds, followed by `track MustExist c'`
 overwriting it.
|No |Same as above.
|===

[cols="1"]
|===
|*Conclusion*
|`track Any c'` since `track MustExist c'` will overwrite in both
cases, but is dependent on `track Any c` in the case of the reference
not existing.
|===

==== track MustExist c' ∘ track MustExist c === track MustExist c'

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |`track MustExist c` succeeds, followed by `track MustExist c'`
 overwriting it.
|No |Both operations are rejected.
|===

[cols="1"]
|===
|*Conclusion*
|`track MustExist c'` will be the final value if the ref exists and it
does not matter in the case of the ref not existing.
|===

==== track MustExist c' ∘ track MustNotExist c === track Any c'

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |`track MustExist c` succeeds, followed by `track MustExist c'`
overwriting it
|No |`track MustNotExist c` succeeds, followed by `track MustExist c'`
overwriting it.
|===

[cols="1"]
|===
|*Conclusion*
|The final value will be `c'` in both cases and should
succeed so we simplify to `track Any c'`.
|===

==== track MustNotExist c' ∘ track Any c === track Any c

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |`track Any c` succeed and `track MustNotExist c'` is rejected.
|No |The same as above.
|===

[cols="1"]
|===
|*Conclusion*
|`track Any c` will be the only successful operation.
|===

==== track MustNotExist c' ∘ track MustExist c === track MustNotExist c' ∘ track MustExist c

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |`track MustExist c` will succeed, while `track MustNotExist c'`
 will be rejected.
|No |`track MustExist c` will be rejected, while `track MustNotExist
 c'` will be succeed.
|===

[cols="1"]
|===
|*Conclusion*
|There is no simplification for this scenario and the
result is purely decided at runtime.
|===

==== track MustNotExist c' ∘ track MustNotExist c === track MustNotExist c

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |Both operations are rejected.
|No |`track MustNotExist c` succeeds which forces `track MustNotExist
  c'` to fail.
|===

[cols="1"]
|===
|*Conclusion*
|`track MustNotExist c` is the winner in the second
scenario, while it will also be rejected in the first. Thus, we keep
it and ignore `track MustNotExist c'`.
|===

=== untrack ∘ untrack

==== untrack Any ∘ x === untrack Any

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |Regardless of the first operation `untrack Any` succeeds.
|No |Both operations will be, at best, noops.
|===

[cols="1"]
|===
|*Conclusion*
|`untrack Any` will always succeed.
|===

==== untrack MustExist ∘ untrack Any === untrack Any

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |`untrack Any` succeeds, then `untrack MustExist`
gets rejected.
|No |`untrack Any` succeeds, leaving the ref
still not existing, and `untrack MustExist` gets rejected.
|===

[cols="1"]
|===
|*Conclusion*
|`untrack Any` will always succeed.
|===

==== untrack MustExist ∘ untrack MustExist === untrack MustExist

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |The first `untrack MustExist` succeeds, the second
is rejected.
|No |Both are rejected, which is the same as a
single one getting rejected.
|===

[cols="1"]
|===
|*Conclusion*
|We can deduplicate to a single `untrack MustExist`.
|===

=== track ∘ untrack

==== track Any ∘ x === track Any

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |The reference would be untracked by `x` but immediately tracked
 again by `track Any`.
|No |`x` will have no effect, while `track Any` will succeed.
|===

[cols="1"]
|===
|*Conclusion*
|`track Any` will ensure the reference is always tracked.
|===

==== track MustExist ∘ untrack p === untrack p

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |`untrack p` will succeed, forcing `track MustExist` to be
 rejected.
|No |`untrack p` has no effect if `p = Any` or rejected if `p =
 MustExist`, leaving `track MustExist` to be rejected.
|===

[cols="1"]
|===
|*Conclusion*
|`untrack p` will succeed or have no effect, while `track MustExist`
will always be rejected.
|===

==== track MustNotExist ∘ x === track Any

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |Either forms of `untrack` will remove the reference, allowing
`track MustNotExist` to succeed.
|No |Either forms of `untrack` will have no effect, leaving the `track
MustNotExist` to succeed.
|===

[cols="1"]
|===
|*Conclusion*
|Since `track MustNotExist` is dependent on the `untrack` in the case
of the ref existing, we can turn it into `track Any` as this chain of
actions representing a forced update.
|===

=== untrack ∘ track

==== untrack Any ∘ x === untrack Any

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |Regardless of any `track` operation, the `untrack` will always
execute leaving the entry untracked.
|No |Similar to the above.
|===

[cols="1"]
|===
|*Conclusion*
|We ignore `x` and keep `untrack Any`.
|===

==== untrack MustExist ∘ x === untrack Any

[cols="1,3"]
|===
|*Ref Exists* |*Reason*
|Yes |Regardless of any `track` operation, the `untrack` will always
execute leaving the entry untracked.
|No |In the cases of the `track` operation being successful, the
`untrack` will leave the entry untracked. If the `track` is rejected,
then `untrack MustExist` will also be rejected.
|===

[cols="1"]
|===
|*Conclusion*
|Since the state will always be left as untracked, we can simplify to
`untrack Any`.
|===

== Appendix

=== Current Implementation

We note that an implementation of tracking exists today. The current
implementation utilises the git `<<config>>` file in the monorepo.
Each URN and Peer ID pairing is stored as a `[remote]` key in the
`config`. One downside to this is that it causes memory pressure as
the file grows with each new remote entry. The other downside is that
multiple processes may try to access the single file concurrently.

=== Banning Peers

While researching and discussing this RFC, it came to our attention
that untracking a peer may not be a permanent action. The protocol
transitively tracks peers through other peers that are tracked. If a
peer is untracked and they are part of the transitive set, then they
will appear as tracked. This is unintuitive from a usability point of
view. This can be partly remedied, however, by denying any extra data
published by this peer, i.e.

[source,json]
----
{
  "data": false,
  "cobs": {
    "*": { "policy": "deny", "pattern": "*" }
  }
}
----

[bibliography]
== References

* [[[RFC2119]]]: https://datatracker.ietf.org/doc/html/rfc2119
* [[[RFC8174]]]: https://datatracker.ietf.org/doc/html/rfc8174
* [[[Canonical-JSON]]]: http://wiki.laptop.org/go/Canonical_JSON
* [[[config]]]: https://git-scm.com/docs/git-config
